version: '3.8'
services:
  app:
    container_name: blog-apprise-local
    image: blog-apprise-local
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    restart: unless-stopped
    environment:
      - PORT=3000
      - NODE_ENV=develop
      - DB_TYPE=postgres
      - DB_HOST=local
      - DB_PORT=5432
      - DB_USERNAME=localhost
      - DB_PASSWORD=123456
      - DB_NAME=nestjs_dev
